#!/bin/bash

export PATH="~/bin:$PATH"

`cat ~/.dmenu.list | dmenu -b -nf '#888888' -nb '#222222' -sf '#ffffff' -sb '#285577'`
#dmenu_path | dmenu -b -nf '#888888' -nb '#222222' -sf '#ffffff' -sb '#285577'